FEE_CLAIMS_TYPE = 1
FEE_UNDERWRITE_TYPE = 2
FEE_SARS_TYPE = 3

FEE_TYPE_CHOICE = (
    (FEE_CLAIMS_TYPE, 'AMRA_CLAIMS'),
    (FEE_UNDERWRITE_TYPE, 'AMRA_UNDERWRITING'),
    (FEE_SARS_TYPE, 'SARS')
)

INVOICE_DRAFT = 'Draft'
INVOICE_PRINTED = 'Printed'

INVOICE_STATUS_CHOICES = (
    (INVOICE_DRAFT, 'Draft'),
    (INVOICE_PRINTED, 'Printed')
)

# Fee status for check setup fee progress.
FEE_STATUS_INVALID_DETAIL = 1
FEE_STATUS_INVALID_FEE = 2
FEE_STATUS_NOT_SETUP_ALL = 3
