# Generated by Django 2.1 on 2018-11-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSnomedConcepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReadCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_read_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SnomedConcept',
            fields=[
                ('external_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('file_path', models.CharField(max_length=255)),
                ('fsn_description', models.CharField(max_length=255)),
                ('external_fsn_description_id', models.BigIntegerField()),
            ],
            options={
                'default_related_name': 'snomed_concepts',
            },
        ),
        migrations.CreateModel(
            name='SnomedDescendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descendant_external_id', models.ForeignKey(db_column='descendant_external_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendant_external_id', to='snomedct.SnomedConcept')),
                ('external_id', models.ForeignKey(db_column='external_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='snomedct.SnomedConcept')),
            ],
        ),
        migrations.AddField(
            model_name='snomedconcept',
            name='children',
            field=models.ManyToManyField(related_name='snomed_concepts', through='snomedct.SnomedDescendant', to='snomedct.SnomedConcept'),
        ),
        migrations.AddField(
            model_name='snomedconcept',
            name='readcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snomed_concepts', to='snomedct.ReadCode'),
        ),
        migrations.AddField(
            model_name='commonsnomedconcepts',
            name='snomed_concept_code',
            field=models.ManyToManyField(to='snomedct.SnomedConcept'),
        ),
        migrations.AddIndex(
            model_name='snomeddescendant',
            index=models.Index(fields=['external_id'], name='snomedct_sn_externa_18ef61_idx'),
        ),
        migrations.AddIndex(
            model_name='snomedconcept',
            index=models.Index(fields=['fsn_description'], name='snomedct_sn_fsn_des_84f149_idx'),
        ),
        migrations.AddIndex(
            model_name='snomedconcept',
            index=models.Index(fields=['external_id'], name='snomedct_sn_externa_21de76_idx'),
        ),
    ]
