# Generated by Django 2.1 on 2018-12-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snomedconcept',
            name='readcode',
        ),
        migrations.AddField(
            model_name='readcode',
            name='concept_id',
            field=models.ForeignKey(db_column='concept_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readcode', to='snomedct.SnomedConcept'),
        ),
    ]
