# Generated by Django 2.1 on 2019-01-30 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0002_auto_20181206_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonsnomedconcepts',
            name='descendant_readcodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonsnomedconcepts',
            name='descendant_snomed_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
