# Generated by Django 2.1 on 2019-03-05 11:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0003_auto_20190130_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonsnomedconcepts',
            name='descendant_readcodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='commonsnomedconcepts',
            name='descendant_snomed_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, null=True, size=None),
        ),
    ]
