# Generated by Django 2.1 on 2018-11-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('max_day_lvl_1', models.PositiveSmallIntegerField(verbose_name='Top payment band until day')),
                ('max_day_lvl_2', models.PositiveSmallIntegerField(verbose_name='Medium payment band until day')),
                ('max_day_lvl_3', models.PositiveSmallIntegerField(verbose_name='Low payment band until day')),
                ('max_day_lvl_4', models.PositiveSmallIntegerField(verbose_name='Lowest payment band after day')),
                ('amount_rate_lvl_1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for top payment band')),
                ('amount_rate_lvl_2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for medium payment band')),
                ('amount_rate_lvl_3', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for low payment band')),
                ('amount_rate_lvl_4', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for lowest payment band')),
                ('gp_practice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationGeneralPractice', verbose_name='General Practice')),
            ],
            options={
                'verbose_name': 'Organisation Fee Structure',
                'verbose_name_plural': 'Organisation Fee Structures',
            },
        ),
    ]
