# Generated by Django 2.1 on 2018-11-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationfee',
            name='created',
        ),
        migrations.RemoveField(
            model_name='organisationfee',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='organisationfee',
            name='modified',
        ),
    ]
