# Generated by Django 2.1 on 2018-12-25 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20181209_1419'),
        ('payment', '0002_auto_20181129_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionVolumeFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_volume_band_lowest', models.PositiveIntegerField(verbose_name='Max volume of Lowest band')),
                ('max_volume_band_low', models.PositiveIntegerField(verbose_name='Max volume of Low band')),
                ('max_volume_band_medium', models.PositiveIntegerField(verbose_name='Max volume of Medium band')),
                ('max_volume_band_top', models.PositiveIntegerField(verbose_name='Max volume of Top band')),
                ('fee_rate_lowest', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for Lowest band(£)')),
                ('fee_rate_low', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for Low band(£)')),
                ('fee_rate_medium', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for Medium band(£)')),
                ('fee_rate_top', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for Top band(£)')),
                ('client_organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationClient', verbose_name='Client Organisation')),
            ],
            options={
                'verbose_name': 'Client Organisation Fee structure',
                'verbose_name_plural': 'Client Organisation Fee structures',
            },
        ),
        migrations.AlterModelOptions(
            name='organisationfee',
            options={'verbose_name': 'GP Organisation Fee Structure', 'verbose_name_plural': 'GP Organisation Fee Structures'},
        ),
    ]
