# Generated by Django 2.1 on 2018-12-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20181225_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionvolumefee',
            options={'verbose_name': 'Client Instruction Volume Fee structure', 'verbose_name_plural': 'Client Instruction Volume Fee structures'},
        ),
        migrations.AddField(
            model_name='instructionvolumefee',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT(%)'),
        ),
    ]
