# Generated by Django 2.1 on 2019-03-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_merge_20190205_0445'),
        ('payment', '0006_auto_20190118_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpOrganisationFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_practice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationGeneralPractice', verbose_name='General Practice')),
            ],
            options={
                'verbose_name': 'GP Organisation Fee Relation',
                'verbose_name_plural': 'GP Organisation Fee Relations',
            },
        ),
        migrations.CreateModel(
            name='OrganisationFeeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_day_lvl_1', models.PositiveSmallIntegerField(default=3, verbose_name='Top payment band until day')),
                ('max_day_lvl_2', models.PositiveSmallIntegerField(default=7, verbose_name='Medium payment band until day')),
                ('max_day_lvl_3', models.PositiveSmallIntegerField(default=11, verbose_name='Low payment band until day')),
                ('max_day_lvl_4', models.PositiveSmallIntegerField(default=12, verbose_name='Lowest payment band after day')),
                ('amount_rate_lvl_1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for top payment band')),
                ('amount_rate_lvl_2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for medium payment band')),
                ('amount_rate_lvl_3', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for low payment band')),
                ('amount_rate_lvl_4', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Earnings for lowest payment band')),
                ('default', models.BooleanField(default=False)),
                ('base', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'GP Organisation Fee Structure',
                'verbose_name_plural': 'GP Organisation Fee Structures',
                'ordering': ['amount_rate_lvl_1'],
            },
        ),
        migrations.RemoveField(
            model_name='organisationfee',
            name='gp_practice',
        ),
        migrations.DeleteModel(
            name='OrganisationFee',
        ),
        migrations.AddField(
            model_name='gporganisationfee',
            name='organisation_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.OrganisationFeeRate', verbose_name='Fee Rate'),
        ),
    ]
