# Generated by Django 2.1 on 2019-03-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_auto_20190313_0844'),
        ('payment', '0007_auto_20190301_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionvolumefee',
            name='client_organisation',
        ),
        migrations.AddField(
            model_name='instructionvolumefee',
            name='client_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationClient', verbose_name='Client Organisation'),
        ),
        migrations.AddField(
            model_name='instructionvolumefee',
            name='fee_rate_type',
            field=models.IntegerField(choices=[(1, 'AMRA_CLAIMS'), (2, 'AMRA_UNDERWRITING'), (3, 'SARS')], default=1, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
