# Generated by Django 2.1 on 2019-03-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20190328_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionvolumefee',
            name='fee_rate_high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Earnings for High band(£)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionvolumefee',
            name='max_volume_band_high',
            field=models.PositiveIntegerField(default=0, verbose_name='Max volume of High band'),
            preserve_default=False,
        ),
    ]
