# Generated by Django 2.1 on 2019-03-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_auto_20190313_0844'),
        ('payment', '0009_auto_20190328_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_instructions', models.IntegerField(default=0, verbose_name='Number Instructions')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total cost in week')),
                ('paid', models.BooleanField(default=False)),
                ('client_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationClient', verbose_name='Client Organisation')),
            ],
        ),
    ]
