# Generated by Django 2.1 on 2019-04-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_weeklyinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyinvoice',
            name='number_instructions',
            field=models.IntegerField(default=0, verbose_name='Number of Instructions'),
        ),
        migrations.AlterField(
            model_name='weeklyinvoice',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total cost in invoice'),
        ),
    ]
