# Generated by Django 2.1 on 2019-04-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20190404_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyinvoice',
            name='weekly_invoice_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
    ]
