# Generated by Django 2.1 on 2019-04-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_weeklyinvoice_weekly_invoice_pdf_file'),
        ('payment', '0012_auto_20190404_0851'),
    ]

    operations = [
    ]
