# Generated by Django 2.1 on 2019-01-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20190128_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyauthorisation',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='thirdpartyauthorisation',
            name='family_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartyauthorisation',
            name='office_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
