# Generated by Django 2.1 on 2019-02-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20190130_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreportauth',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient'),
        ),
    ]
