# Generated by Django 2.1.5 on 2019-02-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_patientreportauth_report_de_activate'),
        ('report', '0006_auto_20190212_0631'),
    ]

    operations = [
    ]
