# Generated by Django 2.1 on 2019-02-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_merge_20190212_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreportauth',
            name='report_de_activate',
        ),
    ]
