# Generated by Django 2.1 on 2019-06-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20190618_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreportauth',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient'),
        ),
    ]
