# Generated by Django 2.1 on 2018-11-21 07:39

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmisAPIConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_organisation_id', models.CharField(max_length=255)),
                ('emis_username', models.CharField(max_length=255)),
                ('emis_password', fernet_fields.fields.EncryptedCharField(max_length=255)),
            ],
        ),
    ]
