# Generated by Django 2.1 on 2019-03-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmisAPIConfig',
        ),
    ]
