# Generated by Django 2.1 on 2019-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_delete_emisapiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_control_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_host', models.CharField(max_length=255)),
                ('gp_access', models.BooleanField(default=False)),
                ('client_access', models.BooleanField(default=False)),
                ('patient_access', models.BooleanField(default=True)),
                ('medi_access', models.BooleanField(default=True)),
                ('active_host', models.BooleanField(default=True)),
            ],
        ),
    ]
