# Generated by Django 2.1 on 2018-11-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[('', '----'), (0, 'Client Admin'), (1, 'Client')], null=True, verbose_name='Role'),
        ),
    ]
