# Generated by Django 2.1 on 2018-11-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_merge_20181127_0440'),
        ('accounts', '0002_auto_20181123_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, choices=[('NEW', 'Email me on each new report request'), ('DIGEST', 'Email me a digest of report requests twice a day'), ('NO', "Don't send me Incoming Report Notifications")], max_length=20)),
                ('contact_feedback', models.BooleanField(blank=True, default=False)),
                ('contact_updates', models.BooleanField(blank=True, default=False)),
                ('gp_organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationGeneralPractice')),
            ],
            options={
                'verbose_name': 'GP Practice Preferences',
            },
        ),
    ]
