# Generated by Django 2.1 on 2018-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_practicepreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicepreferences',
            name='contact_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practicepreferences',
            name='contact_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practicepreferences',
            name='notification',
            field=models.CharField(choices=[('NEW', 'Email me on each new report request'), ('DIGEST', 'Email me a digest of report requests twice a day'), ('NO', "Don't send me Incoming Report Notifications")], default='NEW', max_length=20),
        ),
    ]
