# Generated by Django 2.1 on 2018-12-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181130_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilebase',
            name='address_name_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
