# Generated by Django 2.1 on 2019-01-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181225_0533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GpPractices',
        ),
    ]
