# Generated by Django 2.1 on 2019-01-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_gppractices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebase',
            name='telephone_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
