# Generated by Django 2.1 on 2019-02-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofilebase_telephone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidatauser',
            name='role',
            field=models.IntegerField(blank=True, choices=[('', '----'), (0, 'Medi Super User'), (1, 'Medi Admin'), (2, 'Medi Team')], null=True, verbose_name='Role'),
        ),
    ]
