# Generated by Django 2.1 on 2019-02-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofilebase_telephone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilebase',
            name='title',
            field=models.CharField(choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MIS', 'Miss'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], max_length=3),
        ),
    ]
