# Generated by Django 2.1 on 2019-02-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190207_0522'),
        ('accounts', '0009_medidatauser_role'),
    ]

    operations = [
    ]
