# Generated by Django 2.1 on 2019-03-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20190215_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[('', '----'), (0, 'Client Manager'), (1, 'Client Administrator')], null=True, verbose_name='Role'),
        ),
    ]
