# Generated by Django 2.1 on 2019-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190312_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilebase',
            name='title',
            field=models.CharField(choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MIS', 'Miss'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('MX', 'Mx.')], max_length=3),
        ),
    ]
