# Generated by Django 2.1 on 2019-05-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190420_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ip', models.GenericIPAddressField()),
                ('to_ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Whitelist',
            },
        ),
    ]
