# Generated by Django 2.1 on 2018-11-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_auto_20181129_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateInstructionAdditionalQuestion',
            new_name='TemplateAdditionalQuestion',
        ),
        migrations.RenameField(
            model_name='templateinstruction',
            old_name='client_organisation',
            new_name='organisation',
        ),
    ]
