# Generated by Django 2.1 on 2018-12-01 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_auto_20181130_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateadditionalquestion',
            name='answer_format',
        ),
        migrations.AlterField(
            model_name='templateadditionalquestion',
            name='question',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='templateconditionsofinterest',
            name='snomedct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept'),
        ),
    ]
