# Generated by Django 2.1 on 2018-12-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_auto_20181201_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateinstruction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ClientUser'),
        ),
    ]
