# Generated by Django 2.1 on 2018-12-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0008_auto_20181225_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateinstruction',
            name='common_snomed_concepts',
            field=models.ManyToManyField(blank=True, null=True, to='snomedct.CommonSnomedConcepts'),
        ),
        migrations.AlterField(
            model_name='templateinstruction',
            name='template_title',
            field=models.CharField(max_length=255),
        ),
    ]
