# Generated by Django 2.1 on 2018-12-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snomedct', '0002_auto_20181206_0819'),
        ('template', '0009_auto_20181225_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAdditionalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snomedct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept')),
            ],
            options={
                'verbose_name': 'Template Instruction Additional Condition',
            },
        ),
        migrations.AlterField(
            model_name='templateinstruction',
            name='common_snomed_concepts',
            field=models.ManyToManyField(to='snomedct.CommonSnomedConcepts'),
        ),
        migrations.AddField(
            model_name='templateadditionalcondition',
            name='template_instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='template.TemplateInstruction'),
        ),
    ]
