# Generated by Django 2.1 on 2018-11-21 07:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snomedct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAllergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=255)),
                ('reaction', models.CharField(max_length=255)),
                ('date_discovered', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalMedicationRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=255)),
                ('dose', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescribed_from', models.DateField(null=True)),
                ('prescribed_to', models.DateField(null=True)),
                ('notes', models.TextField()),
                ('repeat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AmendmentsForRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_notes', models.TextField(blank=True)),
                ('acute_prescription_notes', models.TextField(blank=True)),
                ('repeat_prescription_notes', models.TextField(blank=True)),
                ('referral_notes', models.TextField(blank=True)),
                ('significant_problem_notes', models.TextField(blank=True)),
                ('attachment_notes', models.TextField(blank=True)),
                ('bloods_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redacted_xpaths', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('re_redacted_codes', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('submit_choice', models.CharField(blank=True, choices=[('PREPARED_AND_SIGNED', 'Prepared and signed directly by'), ('PREPARED_AND_REVIEWED', 'Prepared by <span id="preparer"></span>  and reviewed by')], max_length=255)),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DRAFT', 'Draft'), ('SUBMIT', 'Submit')], default='NEW', max_length=6)),
                ('comment_notes', models.TextField(blank=True)),
                ('instruction_checked', models.BooleanField(blank=True, default=False, null=True)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction')),
                ('review_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NhsSensitiveConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=128)),
                ('snome_code', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='additionalmedicationrecords',
            name='amendments_for_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalreport.AmendmentsForRecord'),
        ),
        migrations.AddField(
            model_name='additionalmedicationrecords',
            name='snomed_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept'),
        ),
        migrations.AddField(
            model_name='additionalallergies',
            name='amendments_for_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalreport.AmendmentsForRecord'),
        ),
    ]
