# Generated by Django 2.1 on 2018-11-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendmentsforrecord',
            name='submit_choice',
            field=models.CharField(blank=True, choices=[('PREPARED_AND_SIGNED', 'Prepared and signed directly by {}'), ('PREPARED_AND_REVIEWED', 'Prepared by <span id="preparer"></span> and reviewed by')], max_length=255),
        ),
    ]
