# Generated by Django 2.1 on 2018-11-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0002_auto_20181127_0537'),
        ('medicalreport', '0002_auto_20181129_0405'),
    ]

    operations = [
    ]
