# Generated by Django 2.1 on 2019-01-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0003_merge_20181130_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePhrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
