# Generated by Django 2.1 on 2019-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalreport', '0004_referencephrases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amendmentsforrecord',
            name='prepared_by',
        ),
        migrations.AlterField(
            model_name='amendmentsforrecord',
            name='submit_choice',
            field=models.CharField(blank=True, choices=[('PREPARED_AND_SIGNED', 'Prepared and signed directly by {}'), ('PREPARED_AND_REVIEWED', 'Signed off by <span id="preparer"></span>')], max_length=255),
        ),
    ]
