# Generated by Django 2.1 on 2019-01-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofilebase_telephone_code'),
        ('medicalreport', '0005_auto_20190118_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendmentsforrecord',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.GeneralPracticeUser'),
        ),
    ]
