# Generated by Django 2.1 on 2019-05-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0052_auto_20190519_1043'),
        ('medicalreport', '0006_amendmentsforrecord_prepared_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactedAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dds_identifier', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('raw_attachment_file_content', models.BinaryField()),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='medical_attachments')),
                ('redacted_count', models.PositiveIntegerField(default=0)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction')),
            ],
        ),
        migrations.AddField(
            model_name='amendmentsforrecord',
            name='raw_medical_xml',
            field=models.TextField(blank=True),
        ),
    ]
