# Generated by Django 2.1 on 2018-11-21 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
        ('snomedct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('completed_signed_off_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rejected_timestamp', models.DateTimeField(blank=True, null=True)),
                ('rejected_note', models.TextField(blank=True)),
                ('rejected_reason', models.IntegerField(blank=True, choices=[(0, 'No suitable patient can be found'), (1, 'The patient is no longer registered at this practice'), (2, 'The consent form is invalid'), (3, 'Inappropriate purpose for Subject Access Request')], null=True)),
                ('type', models.CharField(choices=[('AMRA', 'AMRA'), ('SARS', 'SARS')], max_length=4)),
                ('final_report_date', models.TextField(blank=True)),
                ('initial_monetary_value', models.FloatField(blank=True, null=True, verbose_name='Value £')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Overdue'), (3, 'Completed'), (4, 'Rejected')], default=0)),
                ('consent_form', models.FileField(blank=True, null=True, upload_to='consent_forms')),
                ('gp_title_from_client', models.CharField(blank=True, choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MX', 'Mx.')], max_length=5)),
                ('gp_initial_from_client', models.CharField(blank=True, max_length=20)),
                ('gp_last_name_from_client', models.CharField(blank=True, max_length=255)),
                ('date_range_from', models.DateField(null=True)),
                ('date_range_to', models.DateField(null=True)),
                ('gp_practice_id', models.CharField(max_length=255)),
                ('sars_consent', models.FileField(blank=True, null=True, upload_to='consent_forms')),
                ('mdx_consent', models.FileField(blank=True, null=True, upload_to='consent_forms')),
                ('saved', models.BooleanField(default=False)),
                ('client_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ClientUser', verbose_name='Client')),
                ('gp_practice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('gp_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.GeneralPracticeUser', verbose_name='GP Allocated')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Instruction',
                'ordering': ('-created',),
                'permissions': (('create_sars', 'Create SARS'), ('reject_amra', 'Reject AMRA'), ('reject_sars', 'Reject SARS'), ('process_amra', 'Process AMRA'), ('process_sars', 'Process SARS'), ('allocate_gp', 'Allocate to other user to process'), ('sign_off_amra', 'Sign off AMRA'), ('sign_off_sars', 'Sign off SARS'), ('view_completed_amra', 'View completed AMRA'), ('view_completed_sars', 'View completed SARS')),
            },
        ),
        migrations.CreateModel(
            name='InstructionAdditionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Instruction Addition Answer',
            },
        ),
        migrations.CreateModel(
            name='InstructionAdditionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255)),
                ('response_mandatory', models.BooleanField(default=False)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addition_questions', to='instructions.Instruction')),
            ],
            options={
                'verbose_name': 'Instruction Addition Question',
            },
        ),
        migrations.CreateModel(
            name='InstructionConditionsOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructions.Instruction')),
                ('snomedct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snomedct.SnomedConcept')),
            ],
            options={
                'verbose_name': 'Instruction Conditions Of Interest',
            },
        ),
        migrations.CreateModel(
            name='InstructionPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_title', models.CharField(choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('MX', 'Mx.')], max_length=3, verbose_name='Title*')),
                ('patient_first_name', models.CharField(max_length=255, verbose_name='First name*')),
                ('patient_last_name', models.CharField(max_length=255, verbose_name='Last name*')),
                ('patient_dob', models.DateField(null=True)),
                ('patient_postcode', models.CharField(max_length=255, verbose_name='Postcode*')),
                ('patient_address_name_number', models.CharField(blank=True, max_length=255)),
                ('patient_address_line2', models.CharField(max_length=255)),
                ('patient_address_line3', models.CharField(max_length=255)),
                ('patient_country', models.CharField(max_length=255)),
                ('patient_nhs_number', models.CharField(blank=True, max_length=10)),
                ('patient_email', models.EmailField(blank=True, max_length=255)),
                ('patient_telephone_mobile', models.CharField(blank=True, max_length=255)),
                ('patient_alternate_phone', models.CharField(blank=True, max_length=255)),
                ('patient_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruction_patients', to='accounts.Patient')),
            ],
            options={
                'verbose_name': 'Instruction Patient Information',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_form', models.FileField(blank=True, null=True, upload_to='consent_forms')),
                ('site', models.URLField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='instructionadditionanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructions.InstructionAdditionQuestion'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='patient_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructions.InstructionPatient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
