# Generated by Django 2.1 on 2018-11-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructionpatient',
            old_name='patient_address_name_number',
            new_name='patient_address_number',
        ),
    ]
