# Generated by Django 2.1 on 2018-11-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_auto_20181121_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionpatient',
            name='patient_address_line1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionpatient',
            name='patient_city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
