# Generated by Django 2.1 on 2018-11-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0003_remove_setting_site'),
        ('instructions', '0003_auto_20181122_1334'),
    ]

    operations = [
    ]
