# Generated by Django 2.1 on 2018-11-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0004_merge_20181126_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionpatient',
            name='patient_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instructionpatient',
            name='patient_address_line3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
