# Generated by Django 2.1 on 2018-12-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0005_auto_20181129_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionpatient',
            name='patient_emis_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
