# Generated by Django 2.1 on 2018-12-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0005_auto_20181129_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionpatient',
            name='patient_alternate_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='instructionpatient',
            name='patient_telephone_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
