# Generated by Django 2.1 on 2018-12-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0006_instructionpatient_patient_emis_number'),
        ('instructions', '0006_auto_20181203_1446'),
    ]

    operations = [
    ]
