# Generated by Django 2.1 on 2018-12-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0007_merge_20181203_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports'),
        ),
    ]
