# Generated by Django 2.1 on 2018-12-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0009_auto_20181207_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='medi_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='your_ref',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
