# Generated by Django 2.1 on 2018-12-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructions', '0009_auto_20181207_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionInternalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='instructions.Instruction')),
            ],
            options={
                'verbose_name': 'Instruction Internal Note',
            },
        ),
    ]
