# Generated by Django 2.1 on 2018-12-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0011_auto_20181217_0912'),
        ('instructions', '0010_auto_20181218_0808'),
    ]

    operations = [
    ]
