# Generated by Django 2.1 on 2018-12-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0012_merge_20181219_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='date_range_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='date_range_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
