# Generated by Django 2.1 on 2018-12-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0013_instructionreminder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionclientnote',
            options={'ordering': ('-created_date',), 'verbose_name': 'Instruction Client Note'},
        ),
    ]
