# Generated by Django 2.1 on 2018-12-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0016_auto_20181226_0534'),
        ('instructions', '0013_auto_20181220_0835'),
    ]

    operations = [
    ]
