# Generated by Django 2.1 on 2018-12-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20181209_1419'),
        ('instructions', '0016_auto_20181226_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='gp_practice_id',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='gp_practice_type',
        ),
        migrations.AddField(
            model_name='instruction',
            name='client_payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instruction',
            name='gp_payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instruction',
            name='gp_practice',
            field=models.ForeignKey(default='Z00094', on_delete=django.db.models.deletion.CASCADE, to='organisations.OrganisationGeneralPractice'),
            preserve_default=False,
        ),
    ]
