# Generated by Django 2.1 on 2018-12-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0017_auto_20181228_0414'),
        ('instructions', '0017_merge_20181227_0734'),
    ]

    operations = [
    ]
