# Generated by Django 2.1 on 2018-12-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0017_auto_20181230_1834'),
        ('instructions', '0018_merge_20181228_0833'),
    ]

    operations = [
    ]
