# Generated by Django 2.1 on 2019-01-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0019_merge_20181230_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='mdx_consent',
            field=models.FileField(blank=True, null=True, upload_to='consent_forms'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='sars_consent',
            field=models.FileField(blank=True, null=True, upload_to='consent_forms'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed'), (3, 'Rejected'), (4, 'Paid')], default=0),
        ),
    ]
