# Generated by Django 2.1 on 2019-01-04 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0020_auto_20190102_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructionpatient',
            old_name='patient_country',
            new_name='patient_county',
        ),
    ]
