# Generated by Django 2.1.4 on 2019-01-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0021_auto_20190104_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='rejected_reason',
            field=models.IntegerField(blank=True, choices=[(0, 'No suitable patient can be found'), (1, 'The patient is no longer registered at this practice'), (2, 'The consent form is invalid'), (3, 'Inappropriate instruction for Subject Access Request')], null=True),
        ),
    ]
