# Generated by Django 2.1 on 2019-02-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0022_auto_20190104_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='medical_xml_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_xml_reports'),
        ),
    ]
