# Generated by Django 2.1.5 on 2019-02-07 05:43

from django.db import migrations
from django.contrib.auth.models import Permission

def forwards_func(apps, schema_editor):
    Permission.objects.filter(codename='view_summry_report').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0024_auto_20190205_0814'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ('-created',), 'permissions': (('create_sars', 'Create SARS'), ('reject_amra', 'Reject AMRA'), ('reject_sars', 'Reject SARS'), ('process_amra', 'Process AMRA'), ('process_sars', 'Process SARS'), ('allocate_gp', 'Allocate to other user to process'), ('sign_off_amra', 'Sign off AMRA'), ('sign_off_sars', 'Sign off SARS'), ('view_completed_amra', 'View completed AMRA'), ('view_completed_sars', 'View completed SARS'), ('view_summary_report', 'View summary report')), 'verbose_name': 'Instruction'},
        ),
    ]
