# Generated by Django 2.1 on 2019-02-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0024_auto_20190205_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='gp_title_from_client',
            field=models.CharField(blank=True, choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MIS', 'Miss'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], max_length=5),
        ),
        migrations.AlterField(
            model_name='instructionpatient',
            name='patient_title',
            field=models.CharField(choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MIS', 'Miss'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], max_length=3, verbose_name='Title*'),
        ),
    ]
