# Generated by Django 2.1 on 2019-02-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0025_auto_20190207_0543'),
        ('instructions', '0025_auto_20190207_0522'),
    ]

    operations = [
    ]
