# Generated by Django 2.1 on 2019-02-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0026_merge_20190215_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='deactivated',
            field=models.BooleanField(default=False, verbose_name='Deactivated at patient request'),
        ),
    ]
