# Generated by Django 2.1 on 2019-02-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0027_instruction_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='medical_with_attachment_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_with_attachment_reports'),
        ),
    ]
