# Generated by Django 2.1 on 2019-03-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0029_auto_20190222_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed'), (3, 'Rejected'), (4, 'Paid'), (5, 'Finalise'), (6, 'Generated Fail')], default=0),
        ),
    ]
