# Generated by Django 2.1 on 2019-03-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0030_instruction_download_attachments'),
        ('instructions', '0030_auto_20190301_0444'),
    ]

    operations = [
    ]
