# Generated by Django 2.1 on 2019-03-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0031_merge_20190301_0837'),
        ('instructions', '0030_instruction_fee_calculation_start_date'),
    ]

    operations = [
    ]
