# Generated by Django 2.1 on 2019-03-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0032_auto_20190301_0951'),
        ('instructions', '0032_merge_20190306_1112'),
    ]

    operations = [
    ]
