# Generated by Django 2.1 on 2019-03-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0033_merge_20190306_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='completed_signed_off_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='medi_ref',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medi Ref.'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='your_ref',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Client Ref.'),
        ),
    ]
