# Generated by Django 2.1 on 2019-03-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0034_auto_20190306_1155'),
        ('instructions', '0034_auto_20190307_1222'),
    ]

    operations = [
    ]
