# Generated by Django 2.1 on 2019-03-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0035_merge_20190308_0741'),
        ('instructions', '0034_auto_20190307_1020'),
    ]

    operations = [
    ]
