# Generated by Django 2.1 on 2019-03-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0036_merge_20190308_0804'),
        ('instructions', '0034_auto_20190308_0416'),
    ]

    operations = [
    ]
