# Generated by Django 2.1 on 2019-03-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0038_auto_20190312_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed'), (3, 'Rejected'), (4, 'Paid'), (5, 'Finalising'), (6, 'Fail')], default=0),
        ),
    ]
