# Generated by Django 2.1 on 2019-03-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0040_auto_20190325_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='type_catagory',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
