# Generated by Django 2.1 on 2019-03-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_weeklyinvoice'),
        ('instructions', '0041_instruction_type_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='invoice_in_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.WeeklyInvoice'),
        ),
    ]
