# Generated by Django 2.1 on 2019-03-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0042_instruction_invoice_in_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='type_catagory',
        ),
        migrations.AddField(
            model_name='instruction',
            name='type_catagory',
            field=models.IntegerField(choices=[(1, 'AMRA_CLAIMS'), (2, 'AMRA_UNDERWRITING'), (3, 'SARS')], null=True),
        ),
    ]
