# Generated by Django 2.1 on 2019-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0044_auto_20190401_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='invoice_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices'),
        ),
    ]
