# Generated by Django 2.1 on 2019-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0045_instruction_invoice_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='gp_title_from_client',
            field=models.CharField(blank=True, choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MIS', 'Miss'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('MX', 'Mx.')], max_length=5),
        ),
        migrations.AlterField(
            model_name='instructionpatient',
            name='patient_title',
            field=models.CharField(choices=[('', '----'), ('DR', 'Dr.'), ('MR', 'Mr.'), ('MIS', 'Miss'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('MX', 'Mx.')], max_length=3, verbose_name='Title*'),
        ),
    ]
