# Generated by Django 2.1 on 2019-04-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0046_auto_20190420_0958'),
        ('instructions', '0047_auto_20190419_0811'),
    ]

    operations = [
    ]
