# Generated by Django 2.1 on 2019-04-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0049_auto_20190425_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='rejected_reason',
            field=models.IntegerField(blank=True, choices=[(0, 'The consent form is invalid'), (1, 'Inappropriate consent / consent not properly obtained'), (2, 'Inappropriate instruction for Subject Access Request'), (3, 'No suitable patient can be found'), (4, 'The instruction can not be processed by the due date'), (5, 'The patient is no longer registered at this practice'), (6, 'The report failed to generate'), (7, 'Cancel instruction by client.')], null=True),
        ),
    ]
