# Generated by Django 2.1 on 2019-05-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0051_auto_20190510_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='final_raw_medical_xml_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='medical_report_byte',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='medical_with_attachment_report_byte',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
