# Generated by Django 2.1 on 2019-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0052_auto_20190519_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='patient_acceptance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='T&C Accpeted Date Time'),
        ),
    ]
