# Generated by Django 2.1 on 2019-06-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0053_instruction_patient_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed'), (3, 'Rejected'), (4, 'Paid'), (5, 'Finalising'), (6, 'Rerun'), (7, 'Redacting')], default=0),
        ),
    ]
