# Generated by Django 2.1 on 2019-06-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0054_auto_20190618_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionpatient',
            name='patient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruction_patients', to='accounts.Patient'),
        ),
    ]
