# Generated by Django 2.1 on 2018-11-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationGeneralPractice',
            fields=[
                ('region', models.CharField(blank=True, max_length=255)),
                ('comm_area', models.CharField(blank=True, max_length=255)),
                ('practcode', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('billing_address_street', models.CharField(blank=True, max_length=255)),
                ('billing_address_city', models.CharField(blank=True, max_length=22)),
                ('billing_address_state', models.CharField(blank=True, max_length=16)),
                ('billing_address_postalcode', models.CharField(blank=True, max_length=8)),
                ('phone_office', models.CharField(blank=True, max_length=28)),
                ('phone_alternate', models.CharField(blank=True, max_length=20)),
                ('organisation_email', models.CharField(blank=True, max_length=255)),
                ('practicemanagername_c', models.CharField(blank=True, max_length=34)),
                ('practicemanager_job_title', models.CharField(blank=True, max_length=47)),
                ('practicemanager_email', models.CharField(blank=True, max_length=54)),
                ('practicemanager_phone', models.CharField(blank=True, max_length=28)),
                ('patientlistsize_c', models.CharField(blank=True, max_length=255)),
                ('sitenumber_c', models.CharField(blank=True, max_length=255)),
                ('employees', models.CharField(blank=True, max_length=2)),
                ('ownership', models.CharField(blank=True, max_length=45)),
                ('ccg_health_board_c', models.CharField(blank=True, max_length=47)),
                ('fax', models.CharField(blank=True, max_length=47)),
                ('gp_operating_system', models.CharField(blank=True, choices=[('EMISWeb', 'EMIS-Web'), ('HealthyV5', 'Healthy V5'), ('LV', 'EMIS-LV'), ('PCS', 'PCS'), ('Practice Manager', 'Practice Manager'), ('PREMIERE', 'Premiere'), ('SYNERGY', 'Synergy'), ('SystmOne', 'SystmOne'), ('Vision 3', 'Vision 3'), ('VA', 'Vision Anywhere'), ('MT', 'Microtest'), ('OT', 'Other')], max_length=32)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('operating_system_socket_endpoint', models.CharField(blank=True, max_length=255)),
                ('operating_system_auth_token', models.CharField(blank=True, max_length=255)),
                ('payment_timing', models.CharField(blank=True, choices=[('AR', 'Arrears'), ('AD', 'Advance')], max_length=2)),
                ('payment_bank_holder_name', models.CharField(blank=True, max_length=255)),
                ('payment_bank_sort_code', models.CharField(blank=True, max_length=255)),
                ('payment_bank_account_number', models.CharField(blank=True, max_length=255)),
                ('payment_preference', models.CharField(blank=True, max_length=255)),
                ('accept_policy', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Organisation GeneralPractice',
            },
        ),
        migrations.CreateModel(
            name='OrganisationMedidata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Organisation Medidata',
            },
        ),
        migrations.CreateModel(
            name='OrganisationBase',
            fields=[
                ('organisationmedidata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organisations.OrganisationMedidata')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_telephone', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('generic_telephone', models.CharField(blank=True, max_length=255)),
                ('generic_email', models.EmailField(blank=True, max_length=254)),
                ('fax_number', models.CharField(blank=True, max_length=255)),
                ('companies_house_number', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Organisation',
                'permissions': (('view_user_management', 'Can view User Management'), ('add_user_management', 'Can add User Management'), ('change_user_management', 'Can change User Management'), ('delete_user_management', 'Can delete User Management')),
            },
            bases=('organisations.organisationmedidata',),
        ),
        migrations.CreateModel(
            name='OrganisationClient',
            fields=[
                ('organisationbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organisations.OrganisationBase')),
                ('type', models.IntegerField(choices=[(1, 'Insurance Underwriter'), (2, 'Insurance Claim'), (3, 'Medicolegal')])),
                ('fca_number', models.CharField(blank=True, max_length=255)),
                ('division', models.TextField(blank=True)),
                ('can_create_amra', models.BooleanField(default=False)),
                ('can_create_sars', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Organisation Client',
            },
            bases=('organisations.organisationbase',),
        ),
    ]
