# Generated by Django 2.1 on 2018-11-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='_operating_system_salt_and_encrypted_password',
            field=models.CharField(blank=True, max_length=511),
        ),
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='operating_system_organisation_code',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='operating_system_salt_and_encrypted_iv',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='operating_system_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
