# Generated by Django 2.1 on 2018-11-23 05:35
from django.db import models
from django.db import migrations
import django.db.models.deletion
from accounts.models import ClientUser, MedidataUser


def delete_user(apps, schema_editor):
    ClientUser.objects.all().hard_delete()
    MedidataUser.objects.all().hard_delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='OrganisationBase'),
        migrations.DeleteModel(name='OrganisationMedidata'),
        migrations.DeleteModel(name='OrganisationClient'),
        migrations.CreateModel(
            name='OrganisationBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Organisation',
                'permissions': (('view_user_management', 'Can view User Management'), ('add_user_management', 'Can add User Management'), ('change_user_management', 'Can change User Management'), ('delete_user_management', 'Can delete User Management')),
            }
        ),
        migrations.CreateModel(
            name='OrganisationClient',
            fields=[
                ('organisationbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organisations.OrganisationBase')),
                ('type', models.IntegerField(choices=[(1, 'Insurance Underwriter'), (2, 'Insurance Claim'), (3, 'Medicolegal')])),
                ('fca_number', models.CharField(blank=True, max_length=255)),
                ('division', models.TextField(blank=True)),
                ('can_create_amra', models.BooleanField(default=False)),
                ('can_create_sars', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Organisation Client',
            },
            bases=('organisations.organisationbase',),
        ),
        migrations.CreateModel(
            name='OrganisationMedidata',
            fields=[
                ('organisationbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organisations.OrganisationBase')),
            ],
            options={
                'verbose_name': 'Organisation Medidata',
            },
            bases=('organisations.organisationbase',),
        ),
    ]
