# Generated by Django 2.1 on 2018-11-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20181123_0633'),
        ('organisations', '0003_auto_20181123_0737'),
    ]

    operations = [
    ]
