# Generated by Django 2.1 on 2018-11-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_merge_20181127_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='billing_address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='billing_address_line_3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
