# Generated by Django 2.1 on 2019-01-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_auto_20181209_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='phone_onboarding_setup',
            field=models.CharField(blank=True, max_length=28, verbose_name='Set-Up Contact Number'),
        ),
    ]
