# Generated by Django 2.1.4 on 2019-01-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisationgeneralpractice_phone_onboarding_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationgeneralpractice',
            name='payment_timing',
            field=models.CharField(blank=True, choices=[('AR', 'Arrears'), ('AD', 'Advance')], default='AR', max_length=2),
        ),
    ]
