# Generated by Django 2.1.4 on 2019-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_auto_20190108_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationgeneralpractice',
            name='live_timechecked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
