# Generated by Django 2.1.4 on 2019-01-18 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0008_auto_20190108_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationbase',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
