# Generated by Django 2.1.5 on 2019-02-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0009_organisationbase_created_time'),
        ('organisations', '0009_organisationgeneralpractice_live_timechecked'),
    ]

    operations = [
    ]
