# Generated by Django 2.1 on 2019-03-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0010_merge_20190205_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationclient',
            name='can_create_amra',
        ),
        migrations.RemoveField(
            model_name='organisationclient',
            name='can_create_sars',
        ),
        migrations.AlterField(
            model_name='organisationclient',
            name='type',
            field=models.IntegerField(choices=[(1, 'Insurer'), (2, 'Reinsurer'), (3, 'Broker'), (4, 'Solicitor'), (5, 'Outsourcer'), (6, 'Government agency'), (7, 'Pharmaceuticals'), (8, 'Research'), (9, 'Other')]),
        ),
    ]
