# Generated by Django 2.1 on 2019-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0011_auto_20190313_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationmedidata',
            name='payment_bank_account_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationmedidata',
            name='payment_bank_holder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationmedidata',
            name='payment_bank_sort_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
