# Generated by Django 2.1 on 2018-11-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMRSetup',
        ),
    ]
